version: 1

formatters:
    standard:
        format: "%(asctime)s.%(msecs)03d | %(message)s"
        datefmt: "%H:%M:%S"

handlers:
    console:
        class: "logging.StreamHandler"
        formatter: "standard"
        stream: "ext://sys.stdout"
    file:
        class: "logging.FileHandler"
        formatter: "standard"
        filename: "/tmp/vasl-templates.log"
        mode: "w"

loggers:
    werkzeug:
        level: "WARNING"
        handlers: [ "file" ]
    vasl_mod:
        level: "WARNING"
        handlers: [ "file" ]
    update_vsav:
        level: "WARNING"
        handlers: [ "file" ]
    analyze_vsav:
        level: "WARNING"
        handlers: [ "file" ]
    analyze_vlog:
        level: "WARNING"
        handlers: [ "file" ]
    webdriver:
        level: "WARNING"
        handlers: [ "file" ]
    downloads:
        level: "WARNING"
        handlers: [ "file" ]
    control_tests:
        level: "INFO"
        handlers: [ "console", "file" ]
